# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_win64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_win64)
  ArtemEngine_config = debug_win64
  Artem_config = debug_win64
  GLFW_config = debug_win64

else ifeq ($(config),debug_linux)
  ArtemEngine_config = debug_linux
  Artem_config = debug_linux
  GLFW_config = debug_linux

else ifeq ($(config),release_win64)
  ArtemEngine_config = release_win64
  Artem_config = release_win64
  GLFW_config = release_win64

else ifeq ($(config),release_linux)
  ArtemEngine_config = release_linux
  Artem_config = release_linux
  GLFW_config = release_linux

else ifeq ($(config),dist_win64)
  ArtemEngine_config = dist_win64
  Artem_config = dist_win64
  GLFW_config = dist_win64

else ifeq ($(config),dist_linux)
  ArtemEngine_config = dist_linux
  Artem_config = dist_linux
  GLFW_config = dist_linux

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := ArtemEngine Artem GLFW

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

ArtemEngine: GLFW
ifneq (,$(ArtemEngine_config))
	@echo "==== Building ArtemEngine ($(ArtemEngine_config)) ===="
	@${MAKE} --no-print-directory -C ArtemEngine -f Makefile config=$(ArtemEngine_config)
endif

Artem: ArtemEngine GLFW
ifneq (,$(Artem_config))
	@echo "==== Building Artem ($(Artem_config)) ===="
	@${MAKE} --no-print-directory -C Artem -f Makefile config=$(Artem_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C GLFW -f Makefile config=$(GLFW_config)
endif

clean:
	@${MAKE} --no-print-directory -C ArtemEngine -f Makefile clean
	@${MAKE} --no-print-directory -C Artem -f Makefile clean
	@${MAKE} --no-print-directory -C GLFW -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_win64"
	@echo "  debug_linux"
	@echo "  release_win64"
	@echo "  release_linux"
	@echo "  dist_win64"
	@echo "  dist_linux"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ArtemEngine"
	@echo "   Artem"
	@echo "   GLFW"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"

run:
	make all
	./bin/Debug-linux-x86_64/Artem/Artem